#! /bin/bash

# LOOPSLICER



# Als er minder dan 2 argumenten worden ingevuld
if [ $# -lt 3 ]; then
  echo "$0: Geef svp filenaam, aantal slices en extensie"
else
  filenaam=$1
  slices=$2
  extensie=$3
  samples=`soxi -s "${filenaam}"`
  dir=$(dirname "${filenaam}") 
  filetype=`soxi -t "${filenaam}"`

 

  echo "filenaam: " `basename "${filenaam}"`
  echo "filetype: " $filetype
  echo "dir:" $dir

  echo "slices: " $slices
  echo "samples:" $samples


# 1 Slice
  
c=$(( `soxi -s "${filenaam}"` / $slices ))
#(( c = `soxi -s $1` / $2))
  echo $c 

# Alleen de bestandsnaam zonder enige toevoeging
name=`basename "${filenaam}" $extensie`
echo "basename:" $name
fi

# Sequentie om X($2) aantal slices te trimmen
for(( i=0; i<$slices; i++ ))

do
  positie=$(($i * $c))s
	`sox "${filenaam}" "${dir}/${name}${i}${extensie}" trim $positie $c"s"`
 echo "newfile:" $name$i 
done