#! /bin/bash

# wav naar mp3 converter


if [ $# -lt 2 ]; then
echo "input must be: Original Filetype and New Filetype"

				


else
	filetype2=$2

	if [[ $filetype2 == .flac ]] || [[ $filetype2 == .mp3 ]] ; then

		filetype1=$1
		echo "old filetype:" $filetype1
		echo "new filetype:" $filetype2
	    echo "are you sure? (y/n)"
	    read answer

	    if [ $answer == y ]; then

	    	for i in *$filetype1

			do 

				#echo $i
				name=`basename "$i" $filetype1`
				dir=$(dirname "$i")
				#echo $i
				if [ $filetype2 == .mp3 ]; then


				 `lame -q0 "$i" "${name}${filetype2}"`	

				else

					if [ $filetype2 == .flac ]; then

						echo "converteren naar .flac"

					else 
				
						echo "Je kunt allen naar .mp3 of .flac converteren"	

					fi
				fi	
			
			done

		else 

			echo "DAN NIET JOH!"


		fi
	
	else

		echo "Je kunt alleen naar .mp3 of .flac converteren"	
	fi
		
fi




