all: optellen printarray maximum roteerarray 

optellen: optellen.cpp
	g++ -c optellen.cpp
	g++ -o optellen optellen.o

printarray: printarray.cpp
	g++ -c printarray.cpp
	g++ -o printarray printarray.o

maximum: maximum.cpp
	g++ -c maximum.cpp
	g++ -o maximum maximum.o

roteerarray: roteerarray.cpp
	g++ -c roteerarray.cpp
	g++ -o roteerarray roteerarray.o
